# Generated by Django 6.0.3 on 2026-04-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ پیدائش'),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_leaving',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ اخراج'),
        ),
        migrations.AddField(
            model_name='student',
            name='desired_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='مطلوبہ درجہ'),
        ),
        migrations.AddField(
            model_name='student',
            name='duration_of_education',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدت تعلیم'),
        ),
        migrations.AddField(
            model_name='student',
            name='father_cnic',
            field=models.CharField(blank=True, max_length=20, verbose_name='والد کا شناختی کارڈ نمبر'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_class_in_jamia',
            field=models.CharField(blank=True, max_length=100, verbose_name='جامعہ میں پہلا درجہ'),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=100, verbose_name='سرپرست کا طالبہ سے رشتہ'),
        ),
        migrations.AddField(
            model_name='student',
            name='left_class_year',
            field=models.CharField(blank=True, max_length=100, verbose_name='کونسے درجے/سال میں چلی گئی'),
        ),
        migrations.AddField(
            model_name='student',
            name='reason_for_leaving',
            field=models.TextField(blank=True, verbose_name='وجہ اخراج'),
        ),
        migrations.AddField(
            model_name='student',
            name='returned_to_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='واپس کونسے درجہ میں آئی'),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='رقم الجلوس'),
        ),
        migrations.AddField(
            model_name='student',
            name='wifaq_registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='وفاق المدارس رقم التسجیل'),
        ),
    ]
