# Generated by Django 6.0.3 on 2026-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_student_date_of_birth_student_date_of_leaving_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='address',
            field=models.TextField(blank=True, verbose_name='پتہ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='assigned_class',
            field=models.CharField(blank=True, max_length=100, verbose_name='کلاس'),
        ),
        migrations.AddField(
            model_name='staff',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='مدت'),
        ),
        migrations.AddField(
            model_name='staff',
            name='salary',
            field=models.CharField(blank=True, max_length=50, verbose_name='تنخواہ'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('شعبہ حفظ و ناظرہ', 'شعبہ حفظ و ناظرہ'), ('شعبہ کتب', 'شعبہ کتب'), ('شعبہ بنین', 'شعبہ بنین')], max_length=50),
        ),
    ]
