# Generated by Django 6.0.3 on 2026-04-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_staff_address_staff_assigned_class_staff_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='انگریزی نام / English Name'),
        ),
    ]
