# Generated by Django 6.0.3 on 2026-04-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_subject_result_obtained_marks_result_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.IntegerField(default=0, verbose_name='ماہانہ خرچہ'),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_contribution',
            field=models.CharField(blank=True, max_length=100, verbose_name='ذاتی تعاون'),
        ),
    ]
