# Generated by Django 6.0.3 on 2026-04-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_result_unique_together_result_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.staff', verbose_name='نگراں استاد'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.staff', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='تنخواہ'),
        ),
    ]
