# Generated by Django 6.0.3 on 2026-04-29 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_student_teacher_subject_teacher_alter_staff_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=50, unique=True, verbose_name='رقم التسجیل / یونیک آئی ڈی')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام (اختیاری)')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رابطہ نمبر')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='رقم')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('description', models.TextField(verbose_name='تفصیل')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='قسم')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='رقم')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ')),
                ('month', models.CharField(blank=True, max_length=20, verbose_name='مہینہ')),
                ('description', models.TextField(blank=True, verbose_name='تفصیل')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='academy.donor', verbose_name='تعاون کنندہ')),
            ],
        ),
    ]
