# Generated by Django 6.0.3 on 2026-04-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0010_donor_expense_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='donor',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
