# Generated by Django 6.0.3 on 2026-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0011_remove_income_donor_delete_expense_delete_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='minutes_late',
            field=models.IntegerField(default=0, verbose_name='تاخیر (منٹ)'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_sahib_tarteeb',
            field=models.BooleanField(default=True, verbose_name='صاحب ترتیب'),
        ),
    ]
