# Generated by Django 6.0.3 on 2026-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_attendance_minutes_late_student_is_sahib_tarteeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_sahib_tarteeb',
            field=models.BooleanField(default=False, verbose_name='صاحب ترتیب'),
        ),
    ]
